#Server
SERVER_PORT: 8080
#Database
MY_SQL_USERNAME: root
MY_SQL_PASSWORD:
POSTGRES_SQL_PORT: 3306
POSTGRES_SQL_DB: supershop
#Email config
EMAIL_HOSTL: smtp.gmail.com
EMAIL_PORT: 587
EMAIl_ID: suppershop@gmail.com
EMAIL_PASSWORD: hhhk alpw dbuh okgg
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}